all:
	rm -r build
	mkdir build
	cd build && cmake .. && cmake --build . 
	@echo ""
	@echo "-----------------------------"
	@echo "Build complete. Running renderer"
	@echo "-----------------------------"
	@echo ""
	./renderer